# Metadata definitions for each lesson
# This file is imported by seeds.exs

[
  %{
    lesson_id: "01_rh_five_fingers",
    key_signature: "C Major",
    scale_type: "major",
    root_note: 60,
    tempo_bpm: 80,
    time_signature_numerator: 4,
    time_signature_denominator: 4,
    rhythm_pattern: "quarter notes",
    starting_position: "C4 (Middle C) - Right hand position 1",
    hand_position_description: "Right hand with thumb on C4, fingers 1-5 on C-D-E-F-G",
    hand_spans: "C4-G4",
    technical_focus: "Hand position, finger independence, basic hand posture",
    difficulty_level: 1,
    recommended_practice_bpm_range: "60-100",
    accuracy_required: 0.9,
    timing_tolerance_ms: 200,
    min_tempo_bpm: 60,
    max_tempo_bpm: 120,
    learning_objectives: Jason.encode!(["Understand correct hand position", "Learn finger numbers", "Develop basic finger independence", "Establish steady tempo"]),
    common_mistakes: Jason.encode!(["Curved fingers become flat", "Wrist too high or too low", "Uneven finger pressure", "Rushing the tempo"]),
    practice_tips: Jason.encode!(["Play slowly and focus on hand shape", "Feel the keys under your fingertips", "Use a metronome for steady tempo", "Practice 5 minutes daily"])
  },

  %{
    lesson_id: "02_rh_skips",
    key_signature: "C Major",
    scale_type: "major",
    root_note: 60,
    tempo_bpm: 80,
    time_signature_numerator: 4,
    time_signature_denominator: 4,
    rhythm_pattern: "quarter notes",
    starting_position: "C4 (Middle C) - Right hand position 1",
    hand_position_description: "Right hand using fingers 1, 2, 3, 5 for skips",
    hand_spans: "C4-G4",
    technical_focus: "Interval recognition, skip technique, hand position maintenance",
    difficulty_level: 2,
    recommended_practice_bpm_range: "70-100",
    accuracy_required: 0.85,
    timing_tolerance_ms: 180,
    min_tempo_bpm: 60,
    max_tempo_bpm: 100,
    learning_objectives: Jason.encode!(["Distinguish between steps and skips", "Develop skip technique", "Maintain hand position"]),
    common_mistakes: Jason.encode!(["Overshooting target note", "Hand position shifts", "Uneven timing", "Tension in hand"]),
    practice_tips: Jason.encode!(["Visualize interval before playing", "Keep wrist relaxed", "Practice slowly", "Build speed gradually"])
  },

  %{
    lesson_id: "03_rh_melody",
    key_signature: "G Major",
    scale_type: "major",
    root_note: 67,
    tempo_bpm: 90,
    time_signature_numerator: 4,
    time_signature_denominator: 4,
    rhythm_pattern: "quarter notes",
    starting_position: "E4",
    hand_position_description: "Right hand starting from finger 3 on E4",
    hand_spans: "C4-G4",
    technical_focus: "Reading melody, phrasing, musical expression, consistent tempo",
    difficulty_level: 2,
    recommended_practice_bpm_range: "70-100",
    accuracy_required: 0.85,
    timing_tolerance_ms: 150,
    min_tempo_bpm: 60,
    max_tempo_bpm: 110,
    learning_objectives: Jason.encode!(["Play a recognizable melody", "Develop phrasing", "Maintain tempo", "Balance accuracy and musicality"]),
    common_mistakes: Jason.encode!(["Rushing familiar parts", "Slowing on difficult passages", "Mechanical playing", "Inconsistent pressure"]),
    practice_tips: Jason.encode!(["Sing melody first", "Play at comfortable tempo", "Add expression gradually", "Record yourself"])
  },

  %{
    lesson_id: "04_rh_rhythm",
    key_signature: "G Major",
    scale_type: "major",
    root_note: 67,
    tempo_bpm: 100,
    time_signature_numerator: 4,
    time_signature_denominator: 4,
    rhythm_pattern: "mixed durations",
    starting_position: "E4",
    hand_position_description: "Right hand, focus on wrist technique for repeated notes",
    hand_spans: "C4-G4",
    technical_focus: "Repeated note control, wrist rotation, rhythm clarity, articulation",
    difficulty_level: 2,
    recommended_practice_bpm_range: "80-120",
    accuracy_required: 0.9,
    timing_tolerance_ms: 140,
    min_tempo_bpm: 70,
    max_tempo_bpm: 130,
    learning_objectives: Jason.encode!(["Master repeated notes", "Develop wrist flexibility", "Clear articulation", "Rhythm precision"]),
    common_mistakes: Jason.encode!(["Blurred notes", "Uneven volume", "Wrist tension", "Rushing tempo"]),
    practice_tips: Jason.encode!(["Use wrist rotation", "Each note should be clear", "Practice slowly", "Listen for separation"])
  }
]
